config {
  type: "view",
  schema: "stg",
  tags: ["stg"]
}

select distinct
    c_custkey,
    c_name,
    c_address,
    c_nationkey,
    c_phone,
    c_acctbal,
    c_mktsegment,
    c_comment,
    n_name,
    n_comment,
    r_name,
    r_comment
from ${ ref('tpch_sf1', 'customer') }
left join ${ ref('tpch_sf1', 'nation') } on c_nationkey = n_nationkey
left join ${ ref('tpch_sf1', 'region') } on n_regionkey = r_regionkey